language: go

install:
  - git clone http://h12.me/socks /home/travis/gopath/src/h12.me/socks
  - go get -t -v ./...

script:
  - go test -v ./...
  - bash ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
